version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    groups:
      cargo-minor-patch:
        update-types:
          - "minor"
          - "patch"
